CREATE TABLE laboratorio (
  id INT NOT NULL,
  activo INT NOT NULL,
  concepto_inactivacion VARCHAR(255),
  descripcion_larga VARCHAR(255),
  descripcion_corta VARCHAR(255) NOT NULL,
  marca VARCHAR(255) NOT NULL,
  modelo VARCHAR(255) NOT NULL,
  serie VARCHAR(255) NOT NULL,
  proveedor_equipo INT NOT NULL,
  fecha_adquisicion DATE NOT NULL,
  garantia_poliza VARCHAR(255),
  garantia_vigencia VARCHAR(255),
  ubicacion VARCHAR(255) NOT NULL,
  responsable_equipo INT NOT NULL,
  mantenimiento_actividad VARCHAR(255) NOT NULL,
  mantenimiento_periodicidad INT NOT NULL,
  mantenimiento_responsable INT NOT NULL,
  analisis_clave_factor INT NOT NULL,
  analisis_nombre_factor VARCHAR(255) NOT NULL,
  analisis_unidad_medida VARCHAR(255) NOT NULL,
  analisis_desviacion VARCHAR(255) NOT NULL,
  analisis_especificacion_interna VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
